### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by kristian-andreasen** [kristian-andreasen/pokemon-trainer#1]
The “Login page” is where the user can enter their “Trainer” name in order to access protected routes (The "Trainer Page" and "Pokémon Catalogue Page"). 
There should be a form to enter the "Trainer" name, and a button that saves the Trainer name to the Trainer API (https://noroff-api-production-c63f.up.railway.app/trainers).

**Comment by JonasAmiri** [comment]
hej
